task completed
StanislauPranovich/webix-start pull request #1
Opened 2022-04-05 17:25 UTC by StanislauPranovich

2022-04-05 18:34 UTC, ILysik commented on index.js
> +var small_film_set = [
Используй либо let, либо const, сделай это по всему файлу. Больше не используй var, но знать про них нужно.

2022-04-05 18:34 UTC, ILysik commented on index.js
> +			label: '<span class="webix_icon wxi-user"></span>' + '<span class="text">Profile</span>',
Это можно сделать в одну строку;
`label: '<span class="webix_icon wxi-user"></span><span class="text">Profile</span>'`
Объединение строк через оператор "+", нужно делать когда в строку нужно вставить какую-то переменную, но и то, для этого сейчас существует строковый шаблон.

2022-04-05 18:34 UTC, ILysik commented on index.js
> +			label: "<span class = 'fas fa-check'></span>" + "<span class = 'connect'>Connected</span>",
Здесь со строкой тоже самое, можно сразу все в одну написать.

2022-04-05 18:34 UTC, ILysik commented on index.js
> +	id: "154",
Странная id. Старайся делать более осознанные названия, чтобы было понятно что оно имеет ввиду.

2022-04-05 18:34 UTC, ILysik commented on index.js
> +	template: "The software is provided by " + "<a href='https://webix.com'>https://webix.com.</a>" + " All rights reserved (c)",
И здесь, не нужно разбивать строку, и объединять через оператор "+", это бессмысленно.

2022-04-05 18:34 UTC, ILysik commented on style.css
> +.webix_template {
Напрямую изменять стили, через названия классов вебикс элементов, плохая практика, потому что ты так изменяешь стили абсолютно во всех элементах в приложении. Я не думаю, что это именно то, чего ты хочешь. Потом придется искать способы как перебить свои же стили. Всегда добавляй свои классы компонентам, и через них изменяй стили элементов, так же это свой класс ты сможешь переиспользовать. Например:
.text-align .webix_template

2022-04-05 18:34 UTC, ILysik commented on style.css
> +.webix_transparent .webix_button {
Здесь с классами такая же история. И везде в стилях тоже исправь.

2022-04-05 20:05 UTC, HelgaListopad requested changes
Сейчас главная проблема в том, что страница не открывается в принципе: в index.html подключается скрипт `testdata.js` (унаследовани из мастера), а здесь есть файл `index.js`
Следует запускать и тестировать свой код перед PR, а также проверять сделанные коммиты.

Мастер трогать уже не нужно, но необходимо исправить имя скрипта в этой ветке.

В Git flow заметка
> (!) студент ничего сам не отправляет в master

подразумевала, что мастер будет пустым.)

2022-04-05 20:05 UTC, HelgaListopad commented on index.js
> +			label: '<span class="webix_icon wxi-user"></span>' + '<span class="text">Profile</span>',
Совсем идеально было бы использовать кнопку соответствующего типа
https://docs.webix.com/desktop__button.html#buttontypesandstyles
```
{ view:"button", type:"icon", icon:"wxi-user", label:"Profile" },
```

2022-04-05 20:05 UTC, HelgaListopad commented on index.js
> +			view: "button",
По заданию тут лучше подойдёт некликабельный label или template

2022-04-05 20:05 UTC, HelgaListopad commented on index.js
> +			width: 220
Общую ширину лучше выставить всей форме

2022-04-05 20:05 UTC, HelgaListopad commented on index.js
> +			height: 230,
Продлевать таким образом высоту layout'a не очень хорошо - лучше разобраться с тем, почему иначе пропадает одно поле.
На лекции мы говорили, что отступы и размеры через CSS выставлять не стоит.
Сейчас у тебя есть глобальный стиль, который добавляет отступы на все поля внутри формы
```css
.webix_el_text {
    padding: 5px 0;
}
```

2022-04-05 20:05 UTC, HelgaListopad commented on index.js
> +				{ view: "text", label: "Title", value: "" },
Пустое value - избыточность, можно убирать.

2022-04-05 20:05 UTC, HelgaListopad commented on index.js
> +				{ width: 10 },
`margin: 10` для `cols` тут всё-таки уместнее

2022-04-05 20:05 UTC, HelgaListopad commented on index.js
> +	height: 750
В этом случае фиксированная высота не подходит, так как UI уже не подстроится под размер браузера.
Если вьюшки внутри сжимают форму, а затем и layout под свой размер (как и происходит, если убрать эту высоту), значит, в форме не хватает spacer'a

2022-04-05 20:05 UTC, HelgaListopad commented on index.js
> +	view: "template",
Этому компоненту нужно задать фиксированную небольшую высоту или `autoheight` (подстроится под контент с учётом его стилей).
Иначе, если всё остальное на странице ресайзится правильно, он займёт почти половину высоты страницы.

2022-04-05 20:05 UTC, HelgaListopad commented on style.css
> +    padding: 5px 0;
Ломает размерность в форме

2022-04-05 20:05 UTC, HelgaListopad commented on style.css
> +    background-color:lightgray;
Чтобы не выставлять один и тот же цвет несколько раз, фону строк (и заодно `border-color`) лучше выставить transparent. Так сразу будет виден основной цвет layout'a.

И да, такие стили не должны быть глобальными (если бы ты добавил ещё один или несколько листов на страницу, каждый из них перенял бы этот стиль)

2022-04-05 20:05 UTC, HelgaListopad commented on index.js
> +	css: "list_background",
Такое название стиля на layout'e несколько путает.
Размещение верное, но нужно переименовать.

2022-04-05 20:29 UTC, StanislauPranovich commented on index.js
> +	id: "154",
айдишка для тестирования просто была, забыл удалить)

2022-04-06 00:25 UTC, StanislauPranovich commented on style.css
> +    background-color:lightgray;
в условии задачи бордеры у полей по пиксель и светлые, поэтому их не трогал)

2022-04-06 10:09 UTC, HelgaListopad requested changes

2022-04-06 10:09 UTC, HelgaListopad commented on index.js
>  	css: "header"
Вместо обычного layout'a тут лучше использовать toolbar cо стилем webix_dark, под который подстроится и прозрачная кнопка 
https://docs.webix.com/desktop__toolbar.html#darktheme

2022-04-06 10:09 UTC, HelgaListopad commented on index.js
> +				{ height: 10},
`margin: 10` для rows - более аккуратный код, чем множество спейсеров.
В целом, структуру можно упростить до той, где берутся стандартные отступы формы
```
	view: "form",
	elements: [		
		{ template: "Edit Films", type: "section" },
		{ view: "text", label: "Title"},
		{ view: "text", label: "Year"},
		{ view: "text", label: "Rating"},
		{ view: "text", label: "Votes"},			
		{
			cols: [
```

2022-04-06 10:09 UTC, HelgaListopad commented on index.js
> +	autoheight: true
`autoheight` здесь ничего не делает, можно убирать

2022-04-06 10:34 UTC, HelgaListopad approved these changes

2022-04-06 10:46 UTC, ILysik approved these changes

2022-04-06 10:46 UTC, merged