lesson2 completed
StanislauPranovich/webix-start pull request #2
Opened 2022-04-06 14:22 UTC by StanislauPranovich

2022-04-06 14:47 UTC, ILysik commented on index.js
> +					click: function () {
Методы объекта можно использовать так `click() {...}` без ключевого слова function

2022-04-06 14:47 UTC, ILysik commented on index.js
> +							$$("main_data").add(item);
В одном блоке кода ты три раза обращаешься к форме через `$$("main_form")`, это значит что ты три раза заставляешь вебикс искать один и тот же компонент, что не очень сказывается на производительности. Лучше один раз получи компонент в переменную, и используй ее во всем блоке кода.

2022-04-06 14:47 UTC, ILysik commented on index.js
> +					click: function() {
`click() {...}` и во всех объектах так исправь.

2022-04-06 14:47 UTC, ILysik commented on index.js
> +								$$("main_form").clearValidation();
Если обращаешься к компоненту `$$("main_form")` более одного раза, сохраняй в переменную.

2022-04-06 14:47 UTC, ILysik commented on index.js
> +							function(){
Здесь актуальней будет стрелочную функцию использовать

2022-04-06 14:47 UTC, ILysik commented on index.js
> +		votes: function (value) {
В этих трех методах year, rating и votes, стрелочная функция будет очень хорошо смотреться
`votes: value => 0 <= value && value <= 100000`

2022-04-06 15:06 UTC, ILysik approved these changes

2022-04-06 22:09 UTC, HelgaListopad requested changes

2022-04-06 22:09 UTC, HelgaListopad commented on index.js
> +webix.ui({
Не сломается, но логически было бы правильнее поменять местами вызовы
```js
webix.ui( popupConfig );  // тут popup с id:"menu"
webix.ui( mainUI );       // тут любая логика, которая задействует ( { view:"button", popup:"menu" } )
```

2022-04-07 09:50 UTC, HelgaListopad approved these changes

2022-04-07 09:51 UTC, merged